----------> uses
# use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#       use GaudiPolicy *  (no_version_directory)
#         use LCG_Settings *  (no_version_directory)
#         use Python * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.3)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use tcmalloc * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.7p3)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use libunwind v* LCG_Interfaces (no_version_directory) (native_version=5c2cade)
#             use LCG_Configuration v*  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#         use Reflex v* LCG_Interfaces (no_auto_imports) (no_version_directory)
#       use AtlasCommonPolicy AtlasCommonPolicy-*  (no_version_directory)
#         use LCG_Platforms *  (no_version_directory)
#         use AtlasDoxygen AtlasDoxygen-* Tools (no_version_directory) (native_version=)
#           use LCG_Settings *  (no_version_directory)
#           use LCG_Configuration *  (no_version_directory)
#             use LCG_Platforms *  (no_version_directory)
#     use Mac105_Compat Mac105_Compat-* External (no_version_directory) (native_version=1.0.0)
#       use AtlasExternalArea AtlasExternalArea-* External (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#         use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#       use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#   use AtlasCxxPolicy AtlasCxxPolicy-*  (no_version_directory)
#     use GaudiPolicy v*  (no_auto_imports) (no_version_directory)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use AtlasCompilers AtlasCompilers-* External (no_version_directory)
#       use LCG_Platforms *  (no_version_directory)
#   use AtlasCommonPolicy AtlasCommonPolicy-*  (no_version_directory)
#   use GaudiPolicy v*  (no_auto_imports) (no_version_directory)
#   use CodeCheck CodeCheck-* Tools (no_version_directory)
#   use AtlasDoxygen AtlasDoxygen-* Tools (no_version_directory) (native_version=)
# use GaudiInterface GaudiInterface-* External (no_version_directory)
#   use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#   use GaudiKernel v*  (no_version_directory)
#     use GaudiPolicy *  (no_version_directory)
#     use GaudiPluginService *  (no_version_directory)
#       use GaudiPolicy *  (no_version_directory)
#     use Reflex * LCG_Interfaces (no_version_directory)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#       use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.13)
#     use Boost * LCG_Interfaces (no_version_directory) (native_version=1.53.0_python2.7)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#       use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.3)
# use TrigSteeringEvent TrigSteeringEvent-* Trigger/TrigEvent (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use CLIDSvc CLIDSvc-* Control (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use CxxUtils CxxUtils-* Control (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AtlasBoost AtlasBoost-* External (no_version_directory)
#           use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#           use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.53.0_python2.7)
#       use AthenaKernel AthenaKernel-* Control (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use uuid v* LCG_Interfaces (no_version_directory) (native_version=1.42)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use DataModelRoot DataModelRoot-* Control (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#             use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#             use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.13)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#               use GCCXML v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=0.9.0_20120309p2)
#                 use LCG_Configuration v*  (no_version_directory)
#                 use LCG_Settings v*  (no_version_directory)
#               use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.3)
#               use xrootd v* LCG_Interfaces (no_version_directory) (native_version=3.2.7)
#                 use LCG_Configuration v*  (no_version_directory)
#                 use LCG_Settings v*  (no_version_directory)
#           use AtlasReflex AtlasReflex-* External (no_version_directory)
#             use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#             use Reflex v* LCG_Interfaces (no_version_directory)
#             use AtlasRELAX AtlasRELAX-00-* External (no_auto_imports) (no_version_directory)
#               use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#               use RELAX v* LCG_Interfaces (no_version_directory) (native_version=RELAX_1_3_0p)
#                 use LCG_Configuration v*  (no_version_directory)
#                 use LCG_Settings v*  (no_version_directory)
#         use CxxUtils CxxUtils-* Control (no_version_directory)
#         use AtlasBoost AtlasBoost-* External (no_version_directory)
#         use Scripts Scripts-* Tools (no_auto_imports) (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use AtlasPython AtlasPython-* External (no_auto_imports) (no_version_directory)
#       use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#       use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.3)
#   use DataModel DataModel-* Control (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use AthAllocators AthAllocators-* Control (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#     use AthLinks AthLinks-* Control (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AthenaKernel AthenaKernel-* Control (no_version_directory)
#       use SGTools SGTools-* Control (no_version_directory)
#       use CxxUtils CxxUtils-* Control (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use AtlasReflex AtlasReflex-* External (no_version_directory)
#     use AthContainers AthContainers-* Control (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AthenaKernel AthenaKernel-* Control (no_version_directory)
#       use SGTools SGTools-* Control (no_version_directory)
#       use CxxUtils CxxUtils-* Control (no_version_directory)
#       use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use CxxUtils CxxUtils-* Control (no_version_directory)
#         use AtlasBoost AtlasBoost-* External (no_version_directory)
#       use AthLinks AthLinks-* Control (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use CxxUtils CxxUtils-* Control (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_version_directory)
#   use DataCollection DataCollection-* External (no_version_directory)
#     use AtlasCxxPolicy AtlasCxxPolicy-*  (no_version_directory)
#     use TDAQCPolicyExt v* TDAQCPolicy (no_version_directory)
#   use SGTools SGTools-* Control (no_version_directory)
#   use TrigSerializeResult TrigSerializeResult-* Trigger/TrigDataAccess (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use CLIDSvc CLIDSvc-* Control (no_version_directory)
#   use TrigConfHLTData TrigConfHLTData-* Trigger/TrigConfiguration (no_version_directory)
#     use DetCommonPolicy *  (no_version_directory)
#       use LCG_Policy *  (no_version_directory)
#         use LCG_Settings *  (no_version_directory)
#       use LCG_Settings *  (no_version_directory)
#       use AtlasCommonPolicy *  (no_version_directory)
#     use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.53.0_python2.7)
#     use TrigConfL1Data TrigConfL1Data-* Trigger/TrigConfiguration (no_version_directory)
#       use DetCommonPolicy *  (no_version_directory)
#       use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.53.0_python2.7)
#   use IRegionSelector IRegionSelector-* DetectorDescription (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AthenaKernel AthenaKernel-* Control (no_version_directory)
#     use CLIDSvc CLIDSvc-* Control (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use Identifier Identifier-* DetectorDescription (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasCxxPolicy AtlasCxxPolicy-*  (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#   use RoiDescriptor RoiDescriptor-* DetectorDescription (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use IRegionSelector IRegionSelector-* DetectorDescription (no_version_directory)
#   use AthenaKernel AthenaKernel-* Control (no_version_directory)
# use TrigTimeAlgs TrigTimeAlgs-* Trigger/TrigTools (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use AtlasROOT AtlasROOT-* External (no_version_directory)
#   use AtlasBoost AtlasBoost-* External (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_version_directory)
#   use AthenaKernel AthenaKernel-* Control (no_version_directory)
#   use DataModel DataModel-* Control (no_version_directory)
#   use SGTools SGTools-* Control (no_version_directory)
# use TrigCaloEvent TrigCaloEvent-* Trigger/TrigEvent (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_version_directory)
#   use DataModel DataModel-* Control (no_version_directory)
#   use Navigation Navigation-* Control (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasBoost AtlasBoost-* External (no_version_directory)
#     use CxxUtils CxxUtils-* Control (no_version_directory)
#     use AthAllocators AthAllocators-* Control (no_version_directory)
#     use AthLinks AthLinks-* Control (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#     use AthenaKernel AthenaKernel-* Control (no_version_directory)
#   use EventKernel EventKernel-* Event (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#       use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#       use CLHEP v* LCG_Interfaces (no_version_directory) (native_version=2.1.2.3)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use Navigation Navigation-* Control (no_version_directory)
#     use VxVertex VxVertex-* Tracking/TrkEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use EventPrimitives EventPrimitives-* Event (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasEigen AtlasEigen-* External (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use PyCmt PyCmt-* Tools (no_auto_imports) (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasPython AtlasPython-* External (no_auto_imports) (no_version_directory)
#           use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#         use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasEigen AtlasEigen-* External (no_version_directory)
#           use EventPrimitives EventPrimitives-* Event (no_version_directory)
#           use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#           use CxxUtils CxxUtils-* Control (no_version_directory)
#       use CLIDSvc CLIDSvc-* Control (no_version_directory)
#       use DataModel DataModel-* Control (no_version_directory)
#       use TrkParameters TrkParameters-* Tracking/TrkEvent (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use TrkParametersBase TrkParametersBase-* Tracking/TrkEvent (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#           use EventPrimitives EventPrimitives-* Event (no_version_directory)
#           use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#         use TrkSurfaces TrkSurfaces-* Tracking/TrkDetDescr (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use DataModel DataModel-* Control (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use Identifier Identifier-* DetectorDescription (no_version_directory)
#           use TrkDetDescrUtils TrkDetDescrUtils-* Tracking/TrkDetDescr (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use CLIDSvc CLIDSvc-* Control (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#             use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#           use TrkDetElementBase TrkDetElementBase-* Tracking/TrkDetDescr (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use Identifier Identifier-* DetectorDescription (no_version_directory)
#             use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#             use GeoModelKernel GeoModelKernel-* DetectorDescription/GeoModel (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasCxxPolicy AtlasCxxPolicy-*  (no_version_directory)
#               use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#             use EventPrimitives EventPrimitives-* Event (no_version_directory)
#           use TrkParametersBase TrkParametersBase-* Tracking/TrkEvent (no_version_directory)
#           use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#           use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#           use EventPrimitives EventPrimitives-* Event (no_version_directory)
#       use TrkNeutralParameters TrkNeutralParameters-* Tracking/TrkEvent (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use TrkParametersBase TrkParametersBase-* Tracking/TrkEvent (no_version_directory)
#         use TrkSurfaces TrkSurfaces-* Tracking/TrkDetDescr (no_version_directory)
#       use TrkTrackLink TrkTrackLink-* Tracking/TrkEvent (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use TrkParameters TrkParameters-* Tracking/TrkEvent (no_version_directory)
#         use TrkNeutralParameters TrkNeutralParameters-* Tracking/TrkEvent (no_version_directory)
#       use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#       use EventPrimitives EventPrimitives-* Event (no_version_directory)
#   use FourMom FourMom-* Event (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#     use EventPrimitives EventPrimitives-* Event (no_version_directory)
#     use EventKernel EventKernel-* Event (no_version_directory)
#   use CLIDSvc CLIDSvc-* Control (no_version_directory)
#   use CaloGeoHelpers CaloGeoHelpers-* Calorimeter (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use CxxUtils CxxUtils-* Control (no_version_directory)
#   use AtlasDoxygen AtlasDoxygen-* Tools (no_version_directory) (native_version=)
#   use SGTools SGTools-* Control (no_version_directory)
#   use TrigMissingEtEvent TrigMissingEtEvent-* Trigger/TrigEvent (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#     use CLIDSvc CLIDSvc-* Control (no_version_directory)
#     use AtlasDoxygen AtlasDoxygen-* Tools (no_version_directory) (native_version=)
#     use SGTools SGTools-* Control (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
# use TrigParticle TrigParticle-* Trigger/TrigEvent (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use CLIDSvc CLIDSvc-* Control (no_version_directory)
#   use DataModel DataModel-* Control (no_version_directory)
#   use Navigation Navigation-* Control (no_version_directory)
#   use EventKernel EventKernel-* Event (no_version_directory)
#   use FourMom FourMom-* Event (no_version_directory)
#   use TrigInDetEvent TrigInDetEvent-* Trigger/TrigEvent (no_version_directory)
#     use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use CLIDSvc CLIDSvc* Control (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#     use EventKernel EventKernel-* Event (no_version_directory)
#     use FourMom FourMom* Event (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use Identifier Identifier-* DetectorDescription (no_version_directory)
#     use InDetPrepRawData InDetPrepRawData-* InnerDetector/InDetRecEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use SGTools SGTools-* Control (no_version_directory)
#       use AthLinks AthLinks-* Control (no_version_directory)
#       use TrkPrepRawData TrkPrepRawData-* Tracking/TrkEvent (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use CLIDSvc CLIDSvc-* Control (no_version_directory)
#         use DataModel DataModel-* Control (no_version_directory)
#         use EventContainers EventContainers-* Event (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use Identifier Identifier-* DetectorDescription (no_version_directory)
#         use Identifier Identifier-* DetectorDescription (no_version_directory)
#         use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#         use EventPrimitives EventPrimitives-* Event (no_version_directory)
#       use Identifier Identifier-* DetectorDescription (no_version_directory)
#       use InDetReadoutGeometry InDetReadoutGeometry-* InnerDetector/InDetDetDescr (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use AthenaKernel AthenaKernel-* Control (no_version_directory)
#         use CLIDSvc CLIDSvc-* Control (no_version_directory)
#         use Identifier Identifier-* DetectorDescription (no_version_directory)
#         use AtlasDetDescr AtlasDetDescr-* DetectorDescription (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use Identifier Identifier-* DetectorDescription (no_version_directory)
#           use IdDict IdDict-* DetectorDescription (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use Identifier Identifier-* DetectorDescription (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#         use GeoModelKernel GeoModelKernel-* DetectorDescription/GeoModel (no_version_directory)
#         use InDetIdentifier InDetIdentifier-* InnerDetector/InDetDetDescr (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasDetDescr AtlasDetDescr-* DetectorDescription (no_version_directory)
#           use Identifier Identifier-* DetectorDescription (no_version_directory)
#           use IdDict IdDict-* DetectorDescription (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#         use InDetCondServices InDetCondServices-* InnerDetector/InDetConditions (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use AthenaKernel AthenaKernel-* Control (no_version_directory)
#           use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#         use TrkDetElementBase TrkDetElementBase-* Tracking/TrkDetDescr (no_version_directory)
#         use TrkSurfaces TrkSurfaces-* Tracking/TrkDetDescr (no_version_directory)
#         use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#         use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#       use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#       use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#       use EventPrimitives EventPrimitives-* Event (no_version_directory)
#       use TrkSurfaces TrkSurfaces-* Tracking/TrkDetDescr (no_version_directory)
#     use Navigation Navigation-* Control (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use TrkPrepRawData TrkPrepRawData-* Tracking/TrkEvent (no_version_directory)
#     use TrkTrack TrkTrack-* Tracking/TrkEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use CLIDSvc CLIDSvc-* Control (no_version_directory)
#       use DataModel DataModel-* Control (no_version_directory)
#       use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#       use TrkParameters TrkParameters-* Tracking/TrkEvent (no_version_directory)
#       use TrkNeutralParameters TrkNeutralParameters-* Tracking/TrkEvent (no_version_directory)
#       use TrkMeasurementBase TrkMeasurementBase-* Tracking/TrkEvent (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use EventPrimitives EventPrimitives-* Event (no_version_directory)
#         use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#         use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#         use DataModel DataModel-* Control (no_version_directory)
#       use TrkMaterialOnTrack TrkMaterialOnTrack-* Tracking/TrkEvent (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#       use TrkTrackLink TrkTrackLink-* Tracking/TrkEvent (no_version_directory)
#     use TrkSpacePoint TrkSpacePoint-* Tracking/TrkEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use EventContainers EventContainers-* Event (no_version_directory)
#       use DataModel DataModel-* Control (no_version_directory)
#       use Identifier Identifier-* DetectorDescription (no_version_directory)
#       use CLIDSvc CLIDSvc-* Control (no_version_directory)
#       use TrkMeasurementBase TrkMeasurementBase-* Tracking/TrkEvent (no_version_directory)
#   use TrigCaloEvent TrigCaloEvent-* Trigger/TrigEvent (no_version_directory)
#   use Particle Particle-* Reconstruction (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use CLIDSvc CLIDSvc-* Control (no_version_directory)
#     use FourMom FourMom-* Event (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use TrkTrack TrkTrack-* Tracking/TrkEvent (no_version_directory)
#     use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#     use VxVertex VxVertex-* Tracking/TrkEvent (no_version_directory)
#     use TrkParameters TrkParameters-* Tracking/TrkEvent (no_version_directory)
#     use TrkTrackSummary TrkTrackSummary-* Tracking/TrkEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use Identifier Identifier-* DetectorDescription (no_version_directory)
#     use TrkParticleBase TrkParticleBase-* Tracking/TrkEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use CLIDSvc CLIDSvc-* Control (no_version_directory)
#       use TrkTrack TrkTrack-* Tracking/TrkEvent (no_version_directory)
#       use TrkEventPrimitives TrkEventPrimitives-* Tracking/TrkEvent (no_version_directory)
#       use VxVertex VxVertex-* Tracking/TrkEvent (no_version_directory)
#       use TrkParameters TrkParameters-* Tracking/TrkEvent (no_version_directory)
#       use DataModel DataModel-* Control (no_version_directory)
#       use TrkTrackLink TrkTrackLink-* Tracking/TrkEvent (no_version_directory)
#       use TrkParameters TrkParameters-* Tracking/TrkEvent (no_version_directory)
#       use TrkNeutralParameters TrkNeutralParameters-* Tracking/TrkEvent (no_version_directory)
#     use EventKernel EventKernel-* Event (no_version_directory)
#     use Navigation Navigation-* Control (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#   use VxVertex VxVertex-* Tracking/TrkEvent (no_version_directory)
#   use SGTools SGTools-* Control (no_version_directory)
# use JetEvent JetEvent-* Reconstruction/Jet (no_version_directory)
#   use SGTools SGTools-* Control (no_version_directory)
#   use CLIDSvc CLIDSvc-* Control (no_version_directory)
#   use DataModel DataModel-* Control (no_version_directory)
#   use Navigation Navigation-* Control (no_version_directory)
#   use StoreGate StoreGate-* Control (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use CxxUtils CxxUtils-* Control (no_version_directory)
#     use AthenaKernel AthenaKernel-* Control (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use AtlasBoost AtlasBoost-* External (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use AthAllocators AthAllocators-* Control (no_version_directory)
#     use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#   use FourMom FourMom-* Event (no_version_directory)
#   use NavFourMom NavFourMom-* Event (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#     use CLIDSvc CLIDSvc-* Control (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#     use EventKernel EventKernel-* Event (no_version_directory)
#     use Navigation Navigation-* Control (no_version_directory)
#   use AtlasBoost AtlasBoost-* External (no_version_directory)
#   use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
#   use ParticleEvent ParticleEvent-* PhysicsAnalysis/AnalysisCommon (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasBoost AtlasBoost-* External (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use Navigation Navigation-* Control (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#     use EventKernel EventKernel-* Event (no_version_directory)
#     use FourMom FourMom-* Event (no_version_directory)
#     use NavFourMom NavFourMom-* Event (no_version_directory)
#     use VxVertex VxVertex-* Tracking/TrkEvent (no_version_directory)
#     use Particle Particle-* Reconstruction (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use EventKernel EventKernel-* Event (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_version_directory)
# use TrigInterfaces TrigInterfaces-* Trigger/TrigSteer (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use StoreGate StoreGate-* Control (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_version_directory)
#   use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use AtlasROOT AtlasROOT-* External (no_version_directory)
#     use AthenaKernel AthenaKernel-* Control (no_version_directory)
#     use StoreGate StoreGate-* Control (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use CxxUtils CxxUtils-* Control (no_version_directory)
#   use AtlasBoost AtlasBoost-* External (no_version_directory)
#   use AthenaMonitoring AthenaMonitoring-* Control (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use AtlasROOT AtlasROOT-* External (no_version_directory)
#     use TrigAnalysisInterfaces TrigAnalysisInterfaces-* Trigger/TrigAnalysis (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AsgTools AsgTools-* Control/AthToolSupport (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use IOVDbDataModel IOVDbDataModel-* Database (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use AthenaPoolUtilities AthenaPoolUtilities-* Database/AthenaPOOL (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#               use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#               use CORAL v* LCG_Interfaces (no_version_directory) (native_version=CORAL_2_4_1)
#                 use LCG_Configuration v*  (no_version_directory)
#                 use LCG_Settings v*  (no_version_directory)
#                 use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.53.0_python2.7)
#                 use uuid v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.42)
#               use AtlasReflex AtlasReflex-00-* External (no_auto_imports) (no_version_directory)
#             use AthenaKernel AthenaKernel-* Control (no_version_directory)
#             use CLIDSvc CLIDSvc-* Control (no_version_directory)
#             use DataModel DataModel-* Control (no_version_directory)
#             use DBDataModel DBDataModel-* Database/AthenaPOOL (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use CLIDSvc CLIDSvc-* Control (no_version_directory)
#               use DataModel DataModel-* Control (no_version_directory)
#           use AthenaKernel AthenaKernel-* Control (no_version_directory)
#     use LumiBlockComps LumiBlockComps-* LumiBlock (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use AthenaKernel AthenaKernel-* Control (no_version_directory)
#       use LumiBlockData LumiBlockData-* LumiBlock (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use DataModel DataModel-* Control (no_version_directory)
#         use CLIDSvc CLIDSvc-* Control (no_version_directory)
#         use AthenaKernel AthenaKernel-* Control (no_version_directory)
#       use AthenaPoolKernel AthenaPoolKernel-* Database/AthenaPOOL (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use AtlasROOT AtlasROOT-* External (no_version_directory)
#       use LumiBlockTPCnv LumiBlockTPCnv-* LumiBlock/LumiBlockPers (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AthenaKernel AthenaKernel-* Control (no_version_directory)
#         use AthenaPoolCnvSvc AthenaPoolCnvSvc-* Database/AthenaPOOL (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasPOOL AtlasPOOL-* External (no_version_directory)
#             use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#             use mysql v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.5.14)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#             use POOLCore POOLCore-* Database/APR (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#               use AtlasBoost AtlasBoost-* External (no_version_directory)
#             use CollectionBase CollectionBase-* Database/APR (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#               use FileCatalog FileCatalog-* Database/APR (no_version_directory)
#                 use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#                 use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#                 use POOLCore POOLCore-* Database/APR (no_version_directory)
#             use CollectionUtilities CollectionUtilities-* Database/APR (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#               use PersistentDataModel PersistentDataModel-* Database (no_version_directory)
#                 use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#                 use GaudiInterface GaudiInterface-* External (no_version_directory)
#                 use SGTools SGTools-* Control (no_version_directory)
#               use CollectionBase CollectionBase-* Database/APR (no_version_directory)
#               use TrigCollQuery TrigCollQuery-* Database/APR (no_version_directory)
#                 use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#                 use GaudiInterface GaudiInterface-* External (no_version_directory)
#                 use AthenaKernel AthenaKernel-* Control (no_version_directory)
#                 use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#             use StorageSvc StorageSvc-* Database/APR (no_version_directory)
#               use uuid * LCG_Interfaces (no_version_directory) (native_version=1.42)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasReflex AtlasReflex-* External (no_version_directory)
#               use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#               use CxxUtils CxxUtils-* Control (no_version_directory)
#               use PersistentDataModel PersistentDataModel-* Database (no_version_directory)
#               use DataModelRoot DataModelRoot-* Control (no_version_directory)
#             use PersistencySvc PersistencySvc-* Database/APR (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use POOLCore POOLCore-* Database/APR (no_version_directory)
#               use StorageSvc StorageSvc-* Database/APR (no_version_directory)
#               use DataModelRoot DataModelRoot-* Control (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use DataModel DataModel-* Control (no_version_directory)
#           use DataModelRoot DataModelRoot-* Control (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use PersistentDataModel PersistentDataModel-* Database (no_version_directory)
#           use AthenaPoolUtilities AthenaPoolUtilities-* Database/AthenaPOOL (no_version_directory)
#           use PoolSvc PoolSvc-* Database/AthenaPOOL (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AtlasPOOL AtlasPOOL-* External (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use DataModelRoot DataModelRoot-* Control (no_version_directory)
#           use TPTools TPTools-* Database (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AthenaKernel AthenaKernel-* Control (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use AthenaPoolUtilities AthenaPoolUtilities-* Database/AthenaPOOL (no_version_directory)
#         use LumiBlockData LumiBlockData-* LumiBlock (no_version_directory)
#       use GoodRunsLists GoodRunsLists-* DataQuality (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#         use AthenaKernel AthenaKernel-* Control (no_version_directory)
#         use AtlasROOT AtlasROOT-* External (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use AtlasCOOL AtlasCOOL-* External (no_version_directory)
#         use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#         use COOL v* LCG_Interfaces (no_version_directory) (native_version=COOL_2_9_1a)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.13)
#           use CORAL v* LCG_Interfaces (no_version_directory) (native_version=CORAL_2_4_1)
#           use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.3)
#         use AtlasReflex AtlasReflex-00-* External (no_auto_imports) (no_version_directory)
#       use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#       use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#   use TrigSteeringEvent TrigSteeringEvent-* Trigger/TrigEvent (no_version_directory)
#   use DataModel DataModel-* Control (no_version_directory)
#   use DataCollection DataCollection-* External (no_version_directory)
#   use TrigNavigation TrigNavigation-* Trigger/TrigEvent (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasBoost AtlasBoost-* External (no_version_directory)
#     use AtlasROOT AtlasROOT-* External (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#     use CLIDSvc CLIDSvc-* Control (no_version_directory)
#     use StoreGate StoreGate-* Control (no_version_directory)
#     use SGTools SGTools-* Control (no_version_directory)
#     use DataModel DataModel-* Control (no_version_directory)
#     use AthContainers AthContainers-* Control (no_version_directory)
#     use AthenaKernel AthenaKernel-* Control (no_version_directory)
#     use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#     use TrigStorageDefinitions TrigStorageDefinitions-* Trigger/TrigEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use DataModel DataModel-* Control (no_version_directory)
#       use Navigation Navigation-* Control (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#       use xAODCaloEvent xAODCaloEvent-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use AthLinks AthLinks-* Control (no_version_directory)
#         use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthenaKernel AthenaKernel-* Control (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#           use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#         use CaloGeoHelpers CaloGeoHelpers-* Calorimeter (no_version_directory)
#         use CaloEvent CaloEvent-* Calorimeter (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use CxxUtils CxxUtils-* Control (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#           use DataModel DataModel-* Control (no_version_directory)
#           use Navigation Navigation-* Control (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use AthAllocators AthAllocators-* Control (no_version_directory)
#           use Identifier Identifier-* DetectorDescription (no_version_directory)
#           use EventKernel EventKernel-* Event (no_version_directory)
#           use FourMom FourMom-* Event (no_version_directory)
#           use NavFourMom NavFourMom-* Event (no_version_directory)
#           use CaloDetDescr CaloDetDescr-* Calorimeter (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AtlasBoost AtlasBoost-* External (no_version_directory)
#             use Identifier Identifier-* DetectorDescription (no_version_directory)
#             use CaloIdentifier CaloIdentifier-* Calorimeter (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use CLIDSvc CLIDSvc-* Control (no_version_directory)
#               use SGTools SGTools-* Control (no_version_directory)
#               use GaudiInterface GaudiInterface-* External (no_version_directory)
#               use AtlasBoost AtlasBoost-* External (no_version_directory)
#               use AtlasDetDescr AtlasDetDescr-* DetectorDescription (no_version_directory)
#               use Identifier Identifier-* DetectorDescription (no_version_directory)
#               use IdDict IdDict-* DetectorDescription (no_version_directory)
#               use GaudiInterface GaudiInterface-* External (no_version_directory)
#               use CaloGeoHelpers CaloGeoHelpers-* Calorimeter (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use CLIDSvc CLIDSvc-* Control (no_version_directory)
#             use DataModel DataModel-* Control (no_version_directory)
#             use AthenaKernel AthenaKernel-* Control (no_version_directory)
#             use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#             use GeoModelInterfaces GeoModelInterfaces-* DetectorDescription/GeoModel (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AthenaKernel AthenaKernel-* Control (no_version_directory)
#               use CLIDSvc CLIDSvc-* Control (no_version_directory)
#               use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use LArReadoutGeometry LArReadoutGeometry-* LArCalorimeter/LArGeoModel (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use CLIDSvc CLIDSvc-* Control (no_version_directory)
#               use GeoModelKernel GeoModelKernel-* DetectorDescription/GeoModel (no_version_directory)
#               use Identifier Identifier-* DetectorDescription (no_version_directory)
#               use LArHV LArHV-* LArCalorimeter/LArGeoModel (no_version_directory)
#                 use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#                 use GeoModelKernel GeoModelKernel-* DetectorDescription/GeoModel (no_version_directory)
#                 use StoreGate StoreGate-* Control (no_version_directory)
#                 use CLIDSvc CLIDSvc-* Control (no_version_directory)
#                 use IOVSvc IOVSvc-* Control (no_version_directory)
#                   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#                   use SGTools SGTools-* Control (no_version_directory)
#                   use AthenaKernel AthenaKernel-* Control (no_version_directory)
#                   use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#                   use AtlasBoost AtlasBoost-* External (no_version_directory)
#                   use GaudiInterface GaudiInterface-* External (no_version_directory)
#               use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#             use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#             use CaloGeoHelpers CaloGeoHelpers-* Calorimeter (no_version_directory)
#           use CaloIdentifier CaloIdentifier-* Calorimeter (no_version_directory)
#           use CaloDetDescr CaloDetDescr-* Calorimeter (no_version_directory)
#           use CaloConditions CaloConditions-* Calorimeter (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use CLIDSvc CLIDSvc-* Control (no_version_directory)
#             use CxxUtils CxxUtils-* Control (no_version_directory)
#             use Identifier Identifier-* DetectorDescription (no_version_directory)
#           use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#           use CaloGeoHelpers CaloGeoHelpers-* Calorimeter (no_version_directory)
#       use xAODEgamma xAODEgamma-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use AtlasROOT AtlasROOT-* External (no_version_directory)
#         use AthLinks AthLinks-* Control (no_version_directory)
#         use CxxUtils CxxUtils-* Control (no_version_directory)
#         use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#         use xAODCaloEvent xAODCaloEvent-* Event/xAOD (no_version_directory)
#         use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#           use EventPrimitives EventPrimitives-* Event (no_version_directory)
#           use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#           use TrkNeutralParameters TrkNeutralParameters-* Tracking/TrkEvent (no_version_directory)
#           use TrkParameters TrkParameters-* Tracking/TrkEvent (no_version_directory)
#           use TrkTrack TrkTrack-* Tracking/TrkEvent (no_version_directory)
#           use VxVertex VxVertex-* Tracking/TrkEvent (no_version_directory)
#           use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#           use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#         use xAODPrimitives xAODPrimitives-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#         use xAODTruth xAODTruth-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#           use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#           use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#           use TruthUtils TruthUtils-* Generators (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AtlasHepMC AtlasHepMC-* External (no_version_directory) (native_version=2.06.08)
#               use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#               use LCG_Configuration v*  (no_version_directory)
#             use AtlasBoost AtlasBoost-* External (no_version_directory)
#             use AtlasFastJet AtlasFastJet-* External (no_version_directory) (native_version=3.0.3)
#               use AtlasExternalArea AtlasExternalArea-00-* External (no_version_directory)
#               use AtlasFortranPolicy AtlasFortranPolicy-*  (no_version_directory) (native_version=gcc-v-4.2.0-20060924)
#                 use AtlasExternalArea AtlasExternalArea-* External (no_version_directory)
#                 use AtlasCompilers AtlasCompilers-* External (no_version_directory)
#                 use GaudiPolicy v*  (no_auto_imports) (no_version_directory)
#             use AtlasROOT AtlasROOT-* External (no_version_directory)
#         use EventPrimitives EventPrimitives-* Event (no_version_directory)
#         use GeoPrimitives GeoPrimitives-* DetectorDescription (no_version_directory)
#       use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#       use xAODMuon xAODMuon-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use AthLinks AthLinks-* Control (no_version_directory)
#         use MuonIdHelpers MuonIdHelpers-* MuonSpectrometer (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#           use AtlasDetDescr AtlasDetDescr-* DetectorDescription (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use IdDict IdDict-* DetectorDescription (no_version_directory)
#           use Identifier Identifier-* DetectorDescription (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use TrkSegment TrkSegment-* Tracking/TrkEvent (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use DataModel DataModel-* Control (no_version_directory)
#           use Identifier Identifier-* DetectorDescription (no_version_directory)
#           use TrkMeasurementBase TrkMeasurementBase-* Tracking/TrkEvent (no_version_directory)
#         use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#         use xAODCaloEvent xAODCaloEvent-* Event/xAOD (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#         use xAODPrimitives xAODPrimitives-* Event/xAOD (no_version_directory)
#         use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#       use xAODTau xAODTau-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use AtlasROOT AtlasROOT-* External (no_version_directory)
#         use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#         use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#         use xAODJet xAODJet-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#           use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#           use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#           use xAODTrigger xAODTrigger-* Event/xAOD (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AthenaKernel AthenaKernel-* Control (no_version_directory)
#             use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#             use AthContainers AthContainers-* Control (no_version_directory)
#             use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#           use xAODBTagging xAODBTagging-* Event/xAOD (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use SGTools SGTools-* Control (no_version_directory)
#             use AthContainers AthContainers-* Control (no_version_directory)
#             use AthLinks AthLinks-* Control (no_version_directory)
#             use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#             use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#             use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#         use xAODPFlow xAODPFlow-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#           use xAODCaloEvent xAODCaloEvent-* Event/xAOD (no_version_directory)
#           use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#           use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#           use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#         use AthLinks AthLinks-* Control (no_version_directory)
#         use xAODTruth xAODTruth-* Event/xAOD (no_version_directory)
#       use xAODJet xAODJet-* Event/xAOD (no_version_directory)
#       use xAODTrigBphys xAODTrigBphys-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use AthLinks AthLinks-* Control (no_version_directory)
#         use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#       use xAODTrigMissingET xAODTrigMissingET-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#       use xAODTrigEgamma xAODTrigEgamma-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#         use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#         use AthLinks AthLinks-* Control (no_version_directory)
#         use xAODTrigCalo xAODTrigCalo-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#           use CaloGeoHelpers CaloGeoHelpers-* Calorimeter (no_version_directory)
#         use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#       use xAODTrigMuon xAODTrigMuon-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use AthLinks AthLinks-* Control (no_version_directory)
#         use xAODBase xAODBase-* Event/xAOD (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#         use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#       use xAODTrigCalo xAODTrigCalo-* Event/xAOD (no_version_directory)
#       use xAODTrigMinBias xAODTrigMinBias-* Event/xAOD (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#       use xAODBTagging xAODBTagging-* Event/xAOD (no_version_directory)
#     use TrigNavStructure TrigNavStructure-* Trigger/TrigEvent (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#   use TrigStorageDefinitions TrigStorageDefinitions-* Trigger/TrigEvent (no_version_directory)
# use GaudiKernel v*  (no_auto_imports) (no_version_directory)
# use GaudiCoreSvc *  (no_auto_imports) (no_version_directory)
#   use GaudiKernel *  (no_version_directory)
#   use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.53.0_python2.7)
#   use ROOT * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.13)
# use CLIDComps * Control (no_auto_imports) (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
# use AtlasCLHEP AtlasCLHEP-* External (no_version_directory)
# use EventKernel EventKernel-* Event (no_version_directory)
# use FourMomUtils FourMomUtils-* Event (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use CxxUtils CxxUtils-* Control (no_version_directory)
#   use EventKernel EventKernel-* Event (no_version_directory)
#   use NavFourMom NavFourMom-* Event (no_version_directory)
# use TrigNavigation TrigNavigation-* Trigger/TrigEvent (no_version_directory)
# use TrigMissingEtEvent TrigMissingEtEvent-* Trigger/TrigEvent (no_version_directory)
# use JetUtils JetUtils-* Reconstruction/Jet (no_version_directory)
#   use xAODCaloEvent xAODCaloEvent-* Event/xAOD (no_version_directory)
#   use FourMomUtils FourMomUtils-* Event (no_version_directory)
#   use xAODTracking xAODTracking-* Event/xAOD (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use xAODJet xAODJet-* Event/xAOD (no_version_directory)
#   use CaloEvent CaloEvent-* Calorimeter (no_version_directory)
#   use AtlasReflex AtlasReflex-* External (no_auto_imports) (no_version_directory)
#   use TestTools TestTools-* AtlasTest (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasPython AtlasPython-* External (no_auto_imports) (no_version_directory)
#     use AthenaCommon AthenaCommon-* Control (no_auto_imports) (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use TestPolicy TestPolicy-*  (no_version_directory)
#       use AtlasPolicy AtlasPolicy-01-*  (no_version_directory)
# use CaloEvent CaloEvent-* Calorimeter (no_version_directory)
# use xAODJet xAODJet-* Event/xAOD (no_version_directory)
# use xAODCaloEvent xAODCaloEvent-* Event/xAOD (no_version_directory)
#
# Selection :
use CMT v1r25p20140131 (/afs/cern.ch/sw/contrib)
use TDAQCPolicyExt v* TDAQCPolicy (/afs/cern.ch/atlas/project/tdaq/prod/tdaq-common/tdaq-common-01-28-00)
use CodeCheck CodeCheck-01-02-03 Tools (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use LCG_Platforms LCG_Platforms-00-67-02-01  (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use AtlasCompilers AtlasCompilers-00-00-20 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use LCG_Configuration LCG_Configuration-00-67-02-01  (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use LCG_Settings v1  (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use mysql v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b) (no_auto_imports)
use CLHEP CLHEP-00-63-00-02 LCG_Interfaces (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use LCG_Policy v1  (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use RELAX v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b) (no_auto_imports)
use uuid v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use AtlasDoxygen AtlasDoxygen-00-04-05 Tools (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use AtlasCommonPolicy AtlasCommonPolicy-00-00-49  (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use DetCommonPolicy DetCommonPolicy-00-00-27  (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use xrootd v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use GCCXML v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b) (no_auto_imports)
use libunwind v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b) (no_auto_imports)
use tcmalloc v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b) (no_auto_imports)
use Python v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b) (no_auto_imports)
use Boost v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use CORAL v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use TrigConfL1Data TrigConfL1Data-02-00-31 Trigger/TrigConfiguration (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use TrigConfHLTData TrigConfHLTData-01-00-25 Trigger/TrigConfiguration (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use ROOT v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use COOL COOL-00-67-02 LCG_Interfaces (/afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5)
use Reflex v1 LCG_Interfaces (/afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b)
use GaudiPolicy GaudiPolicy-15-00-01  (/afs/cern.ch/atlas/software/builds/nightlies/devval/GAUDI/rel_5)
use GaudiPluginService GaudiPluginService-01-02-00  (/afs/cern.ch/atlas/software/builds/nightlies/devval/GAUDI/rel_5)
use GaudiKernel GaudiKernel-31-00-00  (/afs/cern.ch/atlas/software/builds/nightlies/devval/GAUDI/rel_5)
use GaudiCoreSvc GaudiCoreSvc-03-01-00  (/afs/cern.ch/atlas/software/builds/nightlies/devval/GAUDI/rel_5) (no_auto_imports)
use PlatformPolicy PlatformPolicy-00-00-18 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasExternalArea AtlasExternalArea-00-00-25 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasFortranPolicy AtlasFortranPolicy-00-00-79  (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasFastJet AtlasFastJet-00-00-25-02 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use Mac105_Compat Mac105_Compat-00-00-01 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use ExternalPolicy ExternalPolicy-00-01-69 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasHepMC AtlasHepMC-00-00-20 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use AtlasCLHEP AtlasCLHEP-00-00-08 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasPython AtlasPython-00-01-07 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5) (no_auto_imports)
use AtlasRELAX AtlasRELAX-00-01-00 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5) (no_auto_imports)
use AtlasReflex AtlasReflex-00-02-51 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasCOOL AtlasCOOL-00-00-11 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasCORAL AtlasCORAL-00-00-10 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasROOT AtlasROOT-02-03-16 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasBoost AtlasBoost-00-00-07 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use GaudiInterface GaudiInterface-01-03-04 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasCxxPolicy AtlasCxxPolicy-00-00-69  (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use DataCollection DataCollection-00-18-06 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasPolicy AtlasPolicy-01-08-16-01  (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use TestPolicy TestPolicy-00-02-03  (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthenaCommon AthenaCommon-03-00-00-00 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5) (no_auto_imports)
use TestTools TestTools-00-07-09 AtlasTest (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use CLIDComps CLIDComps-00-06-13-01 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5) (no_auto_imports)
use TrigNavStructure TrigNavStructure-00-00-03 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TruthUtils TruthUtils-02-00-07 Generators (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use POOLCore POOLCore-00-04-03 Database/APR (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use FileCatalog FileCatalog-00-01-06 Database/APR (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use CollectionBase CollectionBase-00-02-04 Database/APR (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthenaPoolKernel AthenaPoolKernel-00-02-00 Database/AthenaPOOL (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use GeoModelKernel GeoModelKernel-00-00-80 DetectorDescription/GeoModel (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use PyCmt PyCmt-00-00-36 Tools (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5) (no_auto_imports)
use AtlasEigen AtlasEigen-00-00-05 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use EventPrimitives EventPrimitives-00-00-45 Event (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use Identifier Identifier-00-09-32 DetectorDescription (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use TrkTrackSummary TrkTrackSummary-00-23-05 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use IdDict IdDict-00-08-19 DetectorDescription (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use EventContainers EventContainers-00-04-16 Event (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthAllocators AthAllocators-00-01-03 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use Scripts Scripts-00-01-87 Tools (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5) (no_auto_imports)
use DataModelRoot DataModelRoot-00-00-15 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use CxxUtils CxxUtils-00-01-37 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use CaloGeoHelpers CaloGeoHelpers-00-00-06 Calorimeter (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use GeoPrimitives GeoPrimitives-00-00-33-02 DetectorDescription (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkDetElementBase TrkDetElementBase-01-00-00 Tracking/TrkDetDescr (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkEventPrimitives TrkEventPrimitives-01-00-11 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkMaterialOnTrack TrkMaterialOnTrack-01-01-09 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkParametersBase TrkParametersBase-01-02-03 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use AthenaKernel AthenaKernel-00-56-15 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use InDetCondServices InDetCondServices-01-00-01 InnerDetector/InDetConditions (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use SGTools SGTools-00-24-02 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use PersistentDataModel PersistentDataModel-00-00-40 Database (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use StorageSvc StorageSvc-00-04-21 Database/APR (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use PersistencySvc PersistencySvc-00-02-04 Database/APR (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthContainersInterfaces AthContainersInterfaces-00-01-30 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use StoreGate StoreGate-02-43-01 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthenaBaseComps AthenaBaseComps-00-06-13 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use IOVSvc IOVSvc-00-07-33 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use GoodRunsLists GoodRunsLists-00-01-06 DataQuality (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigCollQuery TrigCollQuery-01-00-03 Database/APR (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use CollectionUtilities CollectionUtilities-00-02-16 Database/APR (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AtlasPOOL AtlasPOOL-00-02-01 External (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use PoolSvc PoolSvc-00-24-06 Database/AthenaPOOL (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthLinks AthLinks-00-02-15 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthContainers AthContainers-00-02-17 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use xAODPrimitives xAODPrimitives-00-00-08 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODCore xAODCore-00-00-71 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTrigMinBias xAODTrigMinBias-00-00-12 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTrigCalo xAODTrigCalo-00-00-04 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTrigMissingET xAODTrigMissingET-00-00-10 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTrigger xAODTrigger-00-00-25-01 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODBase xAODBase-00-00-22 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTruth xAODTruth-00-01-07 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use DataModel DataModel-00-23-71 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use TrkMeasurementBase TrkMeasurementBase-02-00-00 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use Navigation Navigation-00-08-24 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use TrigTimeAlgs TrigTimeAlgs-00-00-41 Trigger/TrigTools (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasTrigger/rel_5)
use CLIDSvc CLIDSvc-00-05-02 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use TrkSegment TrkSegment-02-00-04 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use CaloConditions CaloConditions-00-01-67 Calorimeter (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use LArHV LArHV-00-00-32 LArCalorimeter/LArGeoModel (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use LArReadoutGeometry LArReadoutGeometry-00-01-00 LArCalorimeter/LArGeoModel (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use GeoModelInterfaces GeoModelInterfaces-00-00-03 DetectorDescription/GeoModel (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use LumiBlockData LumiBlockData-00-00-06 LumiBlock (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use DBDataModel DBDataModel-00-08-02 Database/AthenaPOOL (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthenaPoolUtilities AthenaPoolUtilities-00-05-04 Database/AthenaPOOL (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use TPTools TPTools-00-00-03 Database (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AthenaPoolCnvSvc AthenaPoolCnvSvc-00-26-15 Database/AthenaPOOL (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use LumiBlockTPCnv LumiBlockTPCnv-00-01-02 LumiBlock/LumiBlockPers (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use LumiBlockComps LumiBlockComps-00-10-13 LumiBlock (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use IOVDbDataModel IOVDbDataModel-00-00-27 Database (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use AsgTools AsgTools-00-00-34 Control/AthToolSupport (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use TrigAnalysisInterfaces TrigAnalysisInterfaces-00-03-01 Trigger/TrigAnalysis (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use AthenaMonitoring AthenaMonitoring-02-01-13 Control (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrkSpacePoint TrkSpacePoint-05-00-02 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use AtlasDetDescr AtlasDetDescr-00-08-04 DetectorDescription (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5)
use MuonIdHelpers MuonIdHelpers-01-02-06 MuonSpectrometer (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use CaloIdentifier CaloIdentifier-00-10-80 Calorimeter (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use CaloDetDescr CaloDetDescr-01-00-11 Calorimeter (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use InDetIdentifier InDetIdentifier-00-10-01 InnerDetector/InDetDetDescr (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkPrepRawData TrkPrepRawData-07-00-03 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigMissingEtEvent TrigMissingEtEvent-00-00-12 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrkDetDescrUtils TrkDetDescrUtils-01-03-00 Tracking/TrkDetDescr (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkSurfaces TrkSurfaces-01-03-01 Tracking/TrkDetDescr (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use InDetReadoutGeometry InDetReadoutGeometry-02-00-14 InnerDetector/InDetDetDescr (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use InDetPrepRawData InDetPrepRawData-02-00-09 InnerDetector/InDetRecEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrkNeutralParameters TrkNeutralParameters-01-00-05 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkParameters TrkParameters-02-00-07 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrkTrackLink TrkTrackLink-01-00-02 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrkTrack TrkTrack-07-00-06 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use VxVertex VxVertex-03-00-11 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTracking xAODTracking-00-12-02 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTrigMuon xAODTrigMuon-00-00-09 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTrigEgamma xAODTrigEgamma-00-00-09 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTrigBphys xAODTrigBphys-00-00-06 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODBTagging xAODBTagging-00-00-24 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODJet xAODJet-00-01-18 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrkParticleBase TrkParticleBase-01-00-04 Tracking/TrkEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use EventKernel EventKernel-00-08-14 Event (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use NavFourMom NavFourMom-00-04-18 Event (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use FourMomUtils FourMomUtils-00-00-31 Event (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use FourMom FourMom-00-03-20 Event (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use CaloEvent CaloEvent-01-08-50 Calorimeter (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODCaloEvent xAODCaloEvent-00-00-76 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use JetUtils JetUtils-02-00-23 Reconstruction/Jet (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODPFlow xAODPFlow-00-00-47 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODTau xAODTau-00-00-32 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODMuon xAODMuon-00-10-00 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use xAODEgamma xAODEgamma-00-01-10 Event/xAOD (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigStorageDefinitions TrigStorageDefinitions-00-00-28 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigNavigation TrigNavigation-00-04-05 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use Particle Particle-02-10-00 Reconstruction (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use ParticleEvent ParticleEvent-00-22-24 PhysicsAnalysis/AnalysisCommon (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use JetEvent JetEvent-01-01-59 Reconstruction/Jet (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigInDetEvent TrigInDetEvent-00-01-44 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigCaloEvent TrigCaloEvent-00-03-48 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigParticle TrigParticle-00-02-30 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use IRegionSelector IRegionSelector-01-00-02 DetectorDescription (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use RoiDescriptor RoiDescriptor-00-00-01 DetectorDescription (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5)
use TrigSerializeResult TrigSerializeResult-00-01-42 Trigger/TrigDataAccess (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigSteeringEvent TrigSteeringEvent-01-03-04 Trigger/TrigEvent (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5)
use TrigInterfaces TrigInterfaces-01-01-54 Trigger/TrigSteer (/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasTrigger/rel_5)
----------> tags
x86_64-slc6-gcc47-opt (from CMTCONFIG) package [LCG_Platforms PlatformPolicy] implies [target-x86_64 target-slc6 target-gcc47 target-opt Linux slc6 64 gcc-4.7 opt x86_64-slc6-gcc47]
ATLAS (from arguments) package [GaudiPolicy] implies [use-shared-dir no-pyzip] applied [ExternalPolicy]
CMTv1 (from CMTVERSION)
CMTr25 (from CMTVERSION)
CMTp20140131 (from CMTVERSION)
Linux (from uname) package [CMT LCG_Platforms AtlasCxxPolicy AtlasPolicy] implies [Unix host-linux cpp_native_dependencies]
CERN (from CMTSITE)
leejr_no_config (from PROJECT) excludes [leejr_config]
leejr_no_root (from PROJECT) excludes [leejr_root]
leejr_cleanup (from PROJECT) excludes [leejr_no_cleanup]
leejr_scripts (from PROJECT) excludes [leejr_no_scripts]
leejr_no_prototypes (from PROJECT) excludes [leejr_prototypes]
leejr_with_installarea (from PROJECT) excludes [leejr_without_installarea]
leejr_without_version_directory (from PROJECT) excludes [leejr_with_version_directory]
leejr (from PROJECT)
AtlasHLT_no_config (from PROJECT) excludes [AtlasHLT_config]
AtlasHLT_no_root (from PROJECT) excludes [AtlasHLT_root]
AtlasHLT_cleanup (from PROJECT) excludes [AtlasHLT_no_cleanup]
AtlasHLT_scripts (from PROJECT) excludes [AtlasHLT_no_scripts]
AtlasHLT_no_prototypes (from PROJECT) excludes [AtlasHLT_prototypes]
AtlasHLT_with_installarea (from PROJECT) excludes [AtlasHLT_without_installarea]
AtlasHLT_without_version_directory (from PROJECT) excludes [AtlasHLT_with_version_directory]
AtlasTrigger_no_config (from PROJECT) excludes [AtlasTrigger_config]
AtlasTrigger_no_root (from PROJECT) excludes [AtlasTrigger_root]
AtlasTrigger_cleanup (from PROJECT) excludes [AtlasTrigger_no_cleanup]
AtlasTrigger_scripts (from PROJECT) excludes [AtlasTrigger_no_scripts]
AtlasTrigger_no_prototypes (from PROJECT) excludes [AtlasTrigger_prototypes]
AtlasTrigger_with_installarea (from PROJECT) excludes [AtlasTrigger_without_installarea]
AtlasTrigger_without_version_directory (from PROJECT) excludes [AtlasTrigger_with_version_directory]
AtlasReconstruction_no_config (from PROJECT) excludes [AtlasReconstruction_config]
AtlasReconstruction_no_root (from PROJECT) excludes [AtlasReconstruction_root]
AtlasReconstruction_cleanup (from PROJECT) excludes [AtlasReconstruction_no_cleanup]
AtlasReconstruction_scripts (from PROJECT) excludes [AtlasReconstruction_no_scripts]
AtlasReconstruction_no_prototypes (from PROJECT) excludes [AtlasReconstruction_prototypes]
AtlasReconstruction_with_installarea (from PROJECT) excludes [AtlasReconstruction_without_installarea]
AtlasReconstruction_without_version_directory (from PROJECT) excludes [AtlasReconstruction_with_version_directory]
AtlasEvent_no_config (from PROJECT) excludes [AtlasEvent_config]
AtlasEvent_no_root (from PROJECT) excludes [AtlasEvent_root]
AtlasEvent_cleanup (from PROJECT) excludes [AtlasEvent_no_cleanup]
AtlasEvent_scripts (from PROJECT) excludes [AtlasEvent_no_scripts]
AtlasEvent_no_prototypes (from PROJECT) excludes [AtlasEvent_prototypes]
AtlasEvent_with_installarea (from PROJECT) excludes [AtlasEvent_without_installarea]
AtlasEvent_without_version_directory (from PROJECT) excludes [AtlasEvent_with_version_directory]
AtlasConditions_no_config (from PROJECT) excludes [AtlasConditions_config]
AtlasConditions_no_root (from PROJECT) excludes [AtlasConditions_root]
AtlasConditions_cleanup (from PROJECT) excludes [AtlasConditions_no_cleanup]
AtlasConditions_scripts (from PROJECT) excludes [AtlasConditions_no_scripts]
AtlasConditions_no_prototypes (from PROJECT) excludes [AtlasConditions_prototypes]
AtlasConditions_with_installarea (from PROJECT) excludes [AtlasConditions_without_installarea]
AtlasConditions_without_version_directory (from PROJECT) excludes [AtlasConditions_with_version_directory]
AtlasCore_no_config (from PROJECT) excludes [AtlasCore_config]
AtlasCore_no_root (from PROJECT) excludes [AtlasCore_root]
AtlasCore_cleanup (from PROJECT) excludes [AtlasCore_no_cleanup]
AtlasCore_scripts (from PROJECT) excludes [AtlasCore_no_scripts]
AtlasCore_no_prototypes (from PROJECT) excludes [AtlasCore_prototypes]
AtlasCore_with_installarea (from PROJECT) excludes [AtlasCore_without_installarea]
AtlasCore_without_version_directory (from PROJECT) excludes [AtlasCore_with_version_directory]
DetCommon_no_config (from PROJECT) excludes [DetCommon_config]
DetCommon_no_root (from PROJECT) excludes [DetCommon_root]
DetCommon_cleanup (from PROJECT) excludes [DetCommon_no_cleanup]
DetCommon_scripts (from PROJECT) excludes [DetCommon_no_scripts]
DetCommon_prototypes (from PROJECT) excludes [DetCommon_no_prototypes]
DetCommon_with_installarea (from PROJECT) excludes [DetCommon_without_installarea]
DetCommon_without_version_directory (from PROJECT) excludes [DetCommon_with_version_directory]
tdaq-common_no_config (from PROJECT) excludes [tdaq-common_config]
tdaq-common_no_root (from PROJECT) excludes [tdaq-common_root]
tdaq-common_cleanup (from PROJECT) excludes [tdaq-common_no_cleanup]
tdaq-common_scripts (from PROJECT) excludes [tdaq-common_no_scripts]
tdaq-common_prototypes (from PROJECT) excludes [tdaq-common_no_prototypes]
tdaq-common_without_installarea (from PROJECT) excludes [tdaq-common_with_installarea]
tdaq-common_without_version_directory (from PROJECT) excludes [tdaq-common_with_version_directory]
LCGCMT_no_config (from PROJECT) excludes [LCGCMT_config]
LCGCMT_no_root (from PROJECT) excludes [LCGCMT_root]
LCGCMT_cleanup (from PROJECT) excludes [LCGCMT_no_cleanup]
LCGCMT_scripts (from PROJECT) excludes [LCGCMT_no_scripts]
LCGCMT_prototypes (from PROJECT) excludes [LCGCMT_no_prototypes]
LCGCMT_with_installarea (from PROJECT) excludes [LCGCMT_without_installarea]
LCGCMT_without_version_directory (from PROJECT) excludes [LCGCMT_with_version_directory]
GAUDI_no_config (from PROJECT) excludes [GAUDI_config]
GAUDI_root (from PROJECT) excludes [GAUDI_no_root]
GAUDI_cleanup (from PROJECT) excludes [GAUDI_no_cleanup]
GAUDI_scripts (from PROJECT) excludes [GAUDI_no_scripts]
GAUDI_prototypes (from PROJECT) excludes [GAUDI_no_prototypes]
GAUDI_with_installarea (from PROJECT) excludes [GAUDI_without_installarea]
GAUDI_without_version_directory (from PROJECT) excludes [GAUDI_with_version_directory]
dqm-common_no_config (from PROJECT) excludes [dqm-common_config]
dqm-common_no_root (from PROJECT) excludes [dqm-common_root]
dqm-common_cleanup (from PROJECT) excludes [dqm-common_no_cleanup]
dqm-common_scripts (from PROJECT) excludes [dqm-common_no_scripts]
dqm-common_prototypes (from PROJECT) excludes [dqm-common_no_prototypes]
dqm-common_without_installarea (from PROJECT) excludes [dqm-common_with_installarea]
dqm-common_without_version_directory (from PROJECT) excludes [dqm-common_with_version_directory]
tdaq_no_config (from PROJECT) excludes [tdaq_config]
tdaq_no_root (from PROJECT) excludes [tdaq_root]
tdaq_cleanup (from PROJECT) excludes [tdaq_no_cleanup]
tdaq_scripts (from PROJECT) excludes [tdaq_no_scripts]
tdaq_prototypes (from PROJECT) excludes [tdaq_no_prototypes]
tdaq_without_installarea (from PROJECT) excludes [tdaq_with_installarea]
tdaq_without_version_directory (from PROJECT) excludes [tdaq_with_version_directory]
x86_64 (from package CMT) package [LCG_Platforms] implies [host-x86_64] applied [CMT]
slc66 (from package CMT) package [PlatformPolicy] implies [host-slc6] applied [CMT]
gcc472 (from package CMT) package [LCG_Platforms] implies [host-gcc47] applied [CMT]
Unix (from package CMT) package [LCG_Platforms] implies [host-unix] excludes [WIN32 Win32]
c_native_dependencies (from package CMT) activated GaudiPolicy
cpp_native_dependencies (from package CMT) activated GaudiPolicy
/afs/cern.ch/atlas/software/builds/nightlies/devval:/afs/cern.ch/atlas/software/builds:/afs/cern.ch/atlas/software/ASG/builds:/afs/cern.ch/atlas/project/tdaq/prod:/afs/cern.ch/atlas/offline/externalnotProject (from package ExternalPolicy) applied [ExternalPolicy]
target-unix (from package LCG_Settings) activated LCG_Platforms
target-x86_64 (from package LCG_Settings) activated LCG_Platforms
target-gcc47 (from package LCG_Settings) package [LCG_Platforms] implies [target-gcc4 target-lcg-compiler lcg-compiler target-c11] activated LCG_Platforms
host-x86_64 (from package LCG_Settings) activated LCG_Platforms
target-slc (from package LCG_Settings) package [LCG_Platforms] implies [target-linux] activated LCG_Platforms
target-gcc (from package LCG_Settings) activated LCG_Platforms
target-gcc4 (from package LCG_Settings) package [LCG_Platforms] implies [target-gcc] activated LCG_Platforms
target-lcg-compiler (from package LCG_Settings) activated LCG_Platforms
host-gcc4 (from package LCG_Platforms) package [LCG_Platforms] implies [host-gcc]
host-gcc47 (from package LCG_Platforms) package [LCG_Platforms] implies [host-gcc4]
host-gcc (from package LCG_Platforms)
host-linux (from package LCG_Platforms) package [LCG_Platforms] implies [host-unix]
host-unix (from package LCG_Platforms)
host-slc6 (from package LCG_Platforms) package [LCG_Platforms] implies [host-slc] activated PlatformPolicy
host-slc (from package LCG_Platforms) package [LCG_Platforms] implies [host-linux] activated PlatformPolicy
target-opt (from package LCG_Platforms)
target-slc6 (from package LCG_Platforms) package [LCG_Platforms] implies [target-slc]
target-linux (from package LCG_Platforms) package [LCG_Platforms] implies [target-unix]
lcg-compiler (from package LCG_Platforms)
target-c11 (from package LCG_Platforms) excludes [RELAX]
ROOT_GE_5_15 (from package LCG_Configuration) applied [LCG_Configuration]
ROOT_GE_5_19 (from package LCG_Configuration) applied [LCG_Configuration]
use-shared-dir (from package GaudiPolicy)
do_genconf (from package GaudiPolicy) applied [AtlasPolicy] activated AtlasPolicy
no-pyzip (from package GaudiPolicy)
separate-debug (from package AtlasCommonPolicy) excludes [no-separate-debug] applied [AtlasCommonPolicy]
NICOS (from package AtlasCommonPolicy) package AtlasCommonPolicy excludes [NICOSrel_nightly] applied [AtlasCommonPolicy]
LCGCMT_INSTALLED (from package PlatformPolicy) applied [PlatformPolicy ExternalPolicy]
block-tdaqc (from package PlatformPolicy) applied [PlatformPolicy ExternalPolicy]
opt (from package PlatformPolicy) package [AtlasPolicy] implies [optimized]
gcc (from package PlatformPolicy)
64 (from package PlatformPolicy) package [PlatformPolicy] implies [target-64]
gcc-4.7 (from package PlatformPolicy) package [PlatformPolicy] implies [gcc47x gcc47 gcc]
gcc47x (from package PlatformPolicy)
gcc47 (from package PlatformPolicy)
slc6 (from package PlatformPolicy)
x86_64-slc6-gcc47 (from package PlatformPolicy)
target-64 (from package PlatformPolicy)
asNeeded (from package PlatformPolicy) applied [PlatformPolicy]
optimized (from package AtlasPolicy) package [AtlasPolicy] implies [opt] excludes [debug]
HasAthenaRunTime (from package AtlasPolicy) applied [AtlasPolicy]
HAVE_GAUDI_PLUGINSVC (from package GaudiPluginService) applied [GaudiPluginService]
ROOTBasicLibs (from package AtlasROOT) applied [AtlasROOT GoodRunsLists]
ROOTCintexLibs (from package AtlasROOT) applied [xAODCore] activated xAODCore
ROOTMathLibs (from package AtlasROOT) applied [GoodRunsLists xAODBase] activated GoodRunsLists
ROOTGenVectorLibs (from package AtlasROOT) applied [xAODTau xAODJet xAODPFlow] activated xAODTau
NEEDS_CORAL_RELATIONAL_ACCESS (from package CORAL) applied [AtlasCORAL] activated AtlasCORAL
NEEDS_CORAL_BASE (from package CORAL) applied [AthenaPoolUtilities] activated AthenaPoolUtilities
NEEDS_PYCOOL (from package COOL) applied [AtlasCOOL] activated AtlasCOOL
xAODCaloEvent_Calorimeter/CaloEvent_nothasPP (from package xAODCaloEvent) applied [xAODCaloEvent]
xAODTracking_Tracking/TrkEvent/TrkNeutralParameters_nothasPP (from package xAODTracking) applied [xAODTracking]
xAODTracking_Tracking/TrkEvent/TrkParameters_nothasPP (from package xAODTracking) applied [xAODTracking]
xAODTracking_Tracking/TrkEvent/TrkTrack_nothasPP (from package xAODTracking) applied [xAODTracking]
xAODTracking_Tracking/TrkEvent/VxVertex_nothasPP (from package xAODTracking) applied [xAODTracking]
HAS_FORTRAN_RUNTIME (from package AtlasFortranPolicy)
HAS_FORTRAN (from package AtlasFortranPolicy)
HAS_GFO (from package AtlasFortranPolicy) package [AtlasFortranPolicy] implies [HAS_FORTRAN HAS_GFO_RUNTIME] applied [AtlasFortranPolicy]
HAS_GFO_RUNTIME (from package AtlasFortranPolicy) package [AtlasFortranPolicy] implies [HAS_FORTRAN_RUNTIME]
xAODMuon_Tracking/TrkEvent/TrkSegment_nothasPP (from package xAODMuon) applied [xAODMuon]
----------> CMTPATH
# Add path /afs/cern.ch/work/l/leejr/NightlyTest from initialization
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasHLT/rel_5 from initialization
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasTrigger/rel_5 from ProjectPath
# Add path /afs/cern.ch/atlas/project/tdaq/prod/tdaq/tdaq-05-04-00 from ProjectPath
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasReconstruction/rel_5 from ProjectPath
# Add path /afs/cern.ch/atlas/project/tdaq/prod/dqm-common/dqm-common-00-26-02 from ProjectPath
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasEvent/rel_5 from ProjectPath
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasConditions/rel_5 from ProjectPath
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasCore/rel_5 from ProjectPath
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/DetCommon/rel_5 from ProjectPath
# Add path /afs/cern.ch/atlas/project/tdaq/prod/tdaq-common/tdaq-common-01-28-00 from ProjectPath
# Add path /afs/cern.ch/atlas/software/builds/nightlies/devval/GAUDI/rel_5 from ProjectPath
# Add path /afs/cern.ch/atlas/offline/external/LCGCMT/LCGCMT_67b from ProjectPath
